import jsPDF from 'jspdf';
import { TaxResult, formatCurrency } from './taxCalculator';

export const generatePDF = (result: TaxResult) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPosition = 20;

  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('TaxWise NG', pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('2026 Tax Summary', pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 15;
  doc.setDrawColor(0);
  doc.line(20, yPosition, pageWidth - 20, yPosition);

  yPosition += 15;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Income Summary', 20, yPosition);

  yPosition += 12;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');

  const summaryItems = [
    { label: 'Monthly Income:', value: formatCurrency(result.monthlyIncome) },
    { label: 'Annual Income:', value: formatCurrency(result.annualIncome) },
    { label: 'Total Annual Tax:', value: formatCurrency(result.totalTax) },
    { label: 'Monthly Tax:', value: formatCurrency(result.monthlyTax) },
    { label: 'Monthly Take-Home Pay:', value: formatCurrency(result.takeHomePay) },
    { label: 'Effective Tax Rate:', value: `${result.effectiveRate.toFixed(1)}%` },
  ];

  summaryItems.forEach((item) => {
    doc.setFont('helvetica', 'normal');
    doc.text(item.label, 20, yPosition);
    doc.setFont('helvetica', 'bold');
    doc.text(item.value, 100, yPosition);
    yPosition += 8;
  });

  yPosition += 10;
  doc.setDrawColor(0);
  doc.line(20, yPosition, pageWidth - 20, yPosition);

  yPosition += 15;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Tax Breakdown by Bracket', 20, yPosition);

  yPosition += 12;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Bracket', 20, yPosition);
  doc.text('Taxable Amount', 70, yPosition);
  doc.text('Rate', 125, yPosition);
  doc.text('Tax', 155, yPosition);

  yPosition += 7;
  doc.setFont('helvetica', 'normal');

  result.breakdown.forEach((item) => {
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }

    doc.text(item.bracket, 20, yPosition);
    doc.text(formatCurrency(item.taxableAmount), 70, yPosition);
    doc.text(`${(item.rate * 100).toFixed(0)}%`, 125, yPosition);
    doc.text(formatCurrency(item.tax), 155, yPosition);
    yPosition += 8;
  });

  yPosition += 15;
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setDrawColor(0);
  doc.line(20, yPosition, pageWidth - 20, yPosition);

  yPosition += 10;
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text('Generated by TaxWise NG', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 5;
  doc.text('Built for Nigerians | Based on 2026 Tax Law', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 5;
  doc.text(`Generated on ${new Date().toLocaleDateString('en-NG')}`, pageWidth / 2, yPosition, { align: 'center' });

  doc.save(`TaxWise-NG-Summary-${Date.now()}.pdf`);
};
